[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules"]
remappings = [
    "@eth-optimism/=node_modules/@eth-optimism/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@tokamak-network/=node_modules/@tokamak-network/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
