[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
env_file = ".env"
remappings = [
    "@eth-optimism/=node_modules/@eth-optimism/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@tokamak-network/=node_modules/@tokamak-network/",
    "hardhat/=node_modules/hardhat/",
]

[rpc_endpoints]
thanosSepolia = "https://rpc.thanos-sepolia.tokamak.network"

[etherscan]
thanosSepolia = { key = "abcd", url = "https://explorer.thanos-sepolia.tokamak.network/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
